/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ui-copyright.component';
const styles_UiCopyrightComponent:any[] = ([] as any[]);
export const RenderType_UiCopyrightComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_UiCopyrightComponent,data:{}});
export function View_UiCopyrightComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(0,(null as any),['\n    © Copyright ',' ','\n  ']))],
      (null as any),(_ck,_v) => {
        var _co:i1.UiCopyrightComponent = _v.component;
        const currVal_0:any = _co.name;
        const currVal_1:any = _co.now;
        _ck(_v,0,0,currVal_0,currVal_1);
      });
}
export function View_UiCopyrightComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'ui-copyright',
      ([] as any[]),(null as any),(null as any),(null as any),View_UiCopyrightComponent_0,
      RenderType_UiCopyrightComponent)),i0.ɵdid(1,49152,(null as any),0,i1.UiCopyrightComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const UiCopyrightComponentNgFactory:i0.ComponentFactory<i1.UiCopyrightComponent> = i0.ɵccf('ui-copyright',
    i1.UiCopyrightComponent,View_UiCopyrightComponent_Host_0,{name:'name'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3JvbWFpbi9EZXNrdG9wL0Zvcm1hdGlvbl9Bbmd1bGFyX0F2YW5jZV8yMDE4XzAzL1VJQ29weXJpZ2h0L3NyYy91aS1jb3B5cmlnaHQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3JvbWFpbi9EZXNrdG9wL0Zvcm1hdGlvbl9Bbmd1bGFyX0F2YW5jZV8yMDE4XzAzL1VJQ29weXJpZ2h0L3NyYy91aS1jb3B5cmlnaHQuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvcm9tYWluL0Rlc2t0b3AvRm9ybWF0aW9uX0FuZ3VsYXJfQXZhbmNlXzIwMThfMDMvVUlDb3B5cmlnaHQvc3JjL3VpLWNvcHlyaWdodC5jb21wb25lbnQudHMuVWlDb3B5cmlnaHRDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3JvbWFpbi9EZXNrdG9wL0Zvcm1hdGlvbl9Bbmd1bGFyX0F2YW5jZV8yMDE4XzAzL1VJQ29weXJpZ2h0L3NyYy91aS1jb3B5cmlnaHQuY29tcG9uZW50LnRzLlVpQ29weXJpZ2h0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgwqkgQ29weXJpZ2h0IHt7bmFtZX19IHt7bm93fX1cbiAgIiwiPHVpLWNvcHlyaWdodD48L3VpLWNvcHlyaWdodD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTs7O1FBQUE7UUFBQTtRQUFBOzs7O29CQ0FBO01BQUE7cUNBQUEsVUFBQTtNQUFBOzs7In0=
