/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ui-copyright.module';
import * as i2 from '@angular/common';
export const UiCopyrightModuleNgFactory:i0.NgModuleFactory<i1.UiCopyrightModule> = i0.ɵcmf(i1.UiCopyrightModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.UiCopyrightModule,i1.UiCopyrightModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3JvbWFpbi9EZXNrdG9wL0Zvcm1hdGlvbl9Bbmd1bGFyX0F2YW5jZV8yMDE4XzAzL1VJQ29weXJpZ2h0L3NyYy91aS1jb3B5cmlnaHQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3JvbWFpbi9EZXNrdG9wL0Zvcm1hdGlvbl9Bbmd1bGFyX0F2YW5jZV8yMDE4XzAzL1VJQ29weXJpZ2h0L3NyYy91aS1jb3B5cmlnaHQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
