/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './ui-copyright.component';
export declare const RenderType_UiCopyrightComponent: i0.RendererType2;
export declare function View_UiCopyrightComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_UiCopyrightComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const UiCopyrightComponentNgFactory: i0.ComponentFactory<i1.UiCopyrightComponent>;
